baseURL: "https://riccardolofaro.it/"
title: Riccardo Lo Faro
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Riccardo Lo Faro
  description: "Riccardo Lo Faro Personal Website"
  keywords: [ Blog, Portfolio, PaperMod ]
  # author: ["Me", "You"] # multiple authors
  images: [ "<link or path of image for opengraph, twitter-cards>" ]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  hideFooter: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Riccardo Lo Faro"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Hey, I'm Riccardo
    subtitle: Not Your Average Software Engineer
    imageUrl: "img-profile-cropped.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Riccardo Lo Faro
  #    buttons:
  #      - name: Posts
  #        url: posts
  #      - name: Tags
  #        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/riccardo-lo-faro-415906128/"
    - name: github
      url: "https://github.com/riccardolf"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: [ "title", "permalink", "summary", "content" ]
menu:
  main:
    - identifier: home
      name: Home
      url:
      weight: 1
    - identifier: about
      name: About
      url: /about
      weight: 2